package xxsg.oracle.apps.ont.stargatev2.osaportal.returnsearch.model.views;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 02 13:41:43 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HeaderResultsVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        HeaderId,
        Returntype,
        Returndate,
        Returnnumber,
        PartyId,
        CustAccountId,
        Client,
        Status,
        Returnamount,
        Orderref,
        Blocktail,
        PaymentMehtodCode,
        Paymentmethod,
        RefundMehtodCode,
        Reimbursmentmethod,
        Reimbursmentdate,
        LoyaltyCard,
        ServiceRequest,
        Cutomerid,
        Emailid,
        TransactionTypeId,
        Selected,
        Lines;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int RETURNTYPE = AttributesEnum.Returntype.index();
    public static final int RETURNDATE = AttributesEnum.Returndate.index();
    public static final int RETURNNUMBER = AttributesEnum.Returnnumber.index();
    public static final int PARTYID = AttributesEnum.PartyId.index();
    public static final int CUSTACCOUNTID = AttributesEnum.CustAccountId.index();
    public static final int CLIENT = AttributesEnum.Client.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int RETURNAMOUNT = AttributesEnum.Returnamount.index();
    public static final int ORDERREF = AttributesEnum.Orderref.index();
    public static final int BLOCKTAIL = AttributesEnum.Blocktail.index();
    public static final int PAYMENTMEHTODCODE = AttributesEnum.PaymentMehtodCode.index();
    public static final int PAYMENTMETHOD = AttributesEnum.Paymentmethod.index();
    public static final int REFUNDMEHTODCODE = AttributesEnum.RefundMehtodCode.index();
    public static final int REIMBURSMENTMETHOD = AttributesEnum.Reimbursmentmethod.index();
    public static final int REIMBURSMENTDATE = AttributesEnum.Reimbursmentdate.index();
    public static final int LOYALTYCARD = AttributesEnum.LoyaltyCard.index();
    public static final int SERVICEREQUEST = AttributesEnum.ServiceRequest.index();
    public static final int CUTOMERID = AttributesEnum.Cutomerid.index();
    public static final int EMAILID = AttributesEnum.Emailid.index();
    public static final int TRANSACTIONTYPEID = AttributesEnum.TransactionTypeId.index();
    public static final int SELECTED = AttributesEnum.Selected.index();
    public static final int LINES = AttributesEnum.Lines.index();

    /**
     * This is the default constructor (do not remove).
     */
    public HeaderResultsVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute HeaderId.
     * @return the HeaderId
     */
    public BigDecimal getHeaderId() {
        return (BigDecimal) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HeaderId.
     * @param value value to set the  HeaderId
     */
    public void setHeaderId(BigDecimal value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Returntype.
     * @return the Returntype
     */
    public String getReturntype() {
        return (String) getAttributeInternal(RETURNTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Returntype.
     * @param value value to set the  Returntype
     */
    public void setReturntype(String value) {
        setAttributeInternal(RETURNTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Returndate.
     * @return the Returndate
     */
    public Timestamp getReturndate() {
        return (Timestamp) getAttributeInternal(RETURNDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Returndate.
     * @param value value to set the  Returndate
     */
    public void setReturndate(Timestamp value) {
        setAttributeInternal(RETURNDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Returnnumber.
     * @return the Returnnumber
     */
    public BigDecimal getReturnnumber() {
        return (BigDecimal) getAttributeInternal(RETURNNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Returnnumber.
     * @param value value to set the  Returnnumber
     */
    public void setReturnnumber(BigDecimal value) {
        setAttributeInternal(RETURNNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PartyId.
     * @return the PartyId
     */
    public Long getPartyId() {
        return (Long) getAttributeInternal(PARTYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PartyId.
     * @param value value to set the  PartyId
     */
    public void setPartyId(Long value) {
        setAttributeInternal(PARTYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustAccountId.
     * @return the CustAccountId
     */
    public Long getCustAccountId() {
        return (Long) getAttributeInternal(CUSTACCOUNTID);
    }

    /**
     * Gets the attribute value for the calculated attribute Client.
     * @return the Client
     */
    public String getClient() {
        return (String) getAttributeInternal(CLIENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Client.
     * @param value value to set the  Client
     */
    public void setClient(String value) {
        setAttributeInternal(CLIENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Status.
     * @return the Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Status.
     * @param value value to set the  Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Returnamount.
     * @return the Returnamount
     */
    public BigDecimal getReturnamount() {
        return (BigDecimal) getAttributeInternal(RETURNAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Returnamount.
     * @param value value to set the  Returnamount
     */
    public void setReturnamount(BigDecimal value) {
        setAttributeInternal(RETURNAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Orderref.
     * @return the Orderref
     */
    public String getOrderref() {
        return (String) getAttributeInternal(ORDERREF);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Orderref.
     * @param value value to set the  Orderref
     */
    public void setOrderref(String value) {
        setAttributeInternal(ORDERREF, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Blocktail.
     * @return the Blocktail
     */
    public String getBlocktail() {
        return (String) getAttributeInternal(BLOCKTAIL);
    }

    /**
     * Gets the attribute value for the calculated attribute PaymentMehtodCode.
     * @return the PaymentMehtodCode
     */
    public String getPaymentMehtodCode() {
        return (String) getAttributeInternal(PAYMENTMEHTODCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PaymentMehtodCode.
     * @param value value to set the  PaymentMehtodCode
     */
    public void setPaymentMehtodCode(String value) {
        setAttributeInternal(PAYMENTMEHTODCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Paymentmethod.
     * @return the Paymentmethod
     */
    public String getPaymentmethod() {
        return (String) getAttributeInternal(PAYMENTMETHOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Paymentmethod.
     * @param value value to set the  Paymentmethod
     */
    public void setPaymentmethod(String value) {
        setAttributeInternal(PAYMENTMETHOD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RefundMehtodCode.
     * @return the RefundMehtodCode
     */
    public String getRefundMehtodCode() {
        return (String) getAttributeInternal(REFUNDMEHTODCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RefundMehtodCode.
     * @param value value to set the  RefundMehtodCode
     */
    public void setRefundMehtodCode(String value) {
        setAttributeInternal(REFUNDMEHTODCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Reimbursmentmethod.
     * @return the Reimbursmentmethod
     */
    public String getReimbursmentmethod() {
        return (String) getAttributeInternal(REIMBURSMENTMETHOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Reimbursmentmethod.
     * @param value value to set the  Reimbursmentmethod
     */
    public void setReimbursmentmethod(String value) {
        setAttributeInternal(REIMBURSMENTMETHOD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Reimbursmentdate.
     * @return the Reimbursmentdate
     */
    public String getReimbursmentdate() {
        return (String) getAttributeInternal(REIMBURSMENTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Reimbursmentdate.
     * @param value value to set the  Reimbursmentdate
     */
    public void setReimbursmentdate(String value) {
        setAttributeInternal(REIMBURSMENTDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LoyaltyCard.
     * @return the LoyaltyCard
     */
    public String getLoyaltyCard() {
        return (String) getAttributeInternal(LOYALTYCARD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LoyaltyCard.
     * @param value value to set the  LoyaltyCard
     */
    public void setLoyaltyCard(String value) {
        setAttributeInternal(LOYALTYCARD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ServiceRequest.
     * @return the ServiceRequest
     */
    public String getServiceRequest() {
        return (String) getAttributeInternal(SERVICEREQUEST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ServiceRequest.
     * @param value value to set the  ServiceRequest
     */
    public void setServiceRequest(String value) {
        setAttributeInternal(SERVICEREQUEST, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Cutomerid.
     * @return the Cutomerid
     */
    public Long getCutomerid() {
        return (Long) getAttributeInternal(CUTOMERID);
    }

    /**
     * Gets the attribute value for the calculated attribute Emailid.
     * @return the Emailid
     */
    public String getEmailid() {
        return (String) getAttributeInternal(EMAILID);
    }

    /**
     * Gets the attribute value for the calculated attribute TransactionTypeId.
     * @return the TransactionTypeId
     */
    public BigDecimal getTransactionTypeId() {
        return (BigDecimal) getAttributeInternal(TRANSACTIONTYPEID);
    }

    /**
     * Gets the attribute value for the calculated attribute Selected.
     * @return the Selected
     */
    public String getSelected() {
        return (String) getAttributeInternal(SELECTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Selected.
     * @param value value to set the  Selected
     */
    public void setSelected(String value) {
        setAttributeInternal(SELECTED, value);
        System.out.println("this is vinay --> " + value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link Lines.
     */
    public RowIterator getLines() {
        return (RowIterator) getAttributeInternal(LINES);
    }
}

