package xxsg.oracle.apps.ont.stargatev2.osaportal.returnsearch.model.views;

import java.util.Date;

import oracle.jbo.format.DefaultDateFormatter;
import oracle.jbo.format.FormatErrorException;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 21 16:28:46 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReturnSearchParamsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ReturnSearchParamsVOImpl() {
    }
}

